### ISSUE TITLE
Crashes when summoning Pet Buddy, Forge 1.11-13.19.1.2188

### ISSUE THREAD

**Issue by TheGriz** [ArtixAllMighty/PetBuddy2016#10]
Hello,

Love the mod. Played it under 10.2 with no problems.
But 1.11 crashes when summoning Pet Buddy

Clean Minecraft and Forge install. No other mods. Forge 1.11-13.19.1.2188

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/7/16 8:00 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376)
	at subaraki.petbuddy.entity.RenderPetBuddy.doRender(RenderPetBuddy.java:73)
	at subaraki.petbuddy.entity.RenderPetBuddy.func_76986_a(RenderPetBuddy.java:49)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:383)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:367)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:626)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1332)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1246)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1075)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376)
	at subaraki.petbuddy.entity.RenderPetBuddy.doRender(RenderPetBuddy.java:73)
	at subaraki.petbuddy.entity.RenderPetBuddy.func_76986_a(RenderPetBuddy.java:49)

-- Entity being rendered --
Details:
	Entity Type: minecraft:pet_buddy (subaraki.petbuddy.entity.EntityPetBuddy)
	Entity ID: 420
	Entity Name: ssfoiles
	Entity's Exact location: -248.82, 64.00, -216.53
	Entity's Block location: World: (-249,64,-217), Chunk: (at 7,4,7 in -16,-14; contains blocks -256,0,-224 to -241,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: subaraki.petbuddy.entity.RenderPetBuddy@61d99b13
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -76.41756
	Delta: 0.6626997
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:383)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:367)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:626)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1332)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1246)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ssfoiles'/310, l='MpServer', x=-248.82, y=64.00, z=-216.53]]
	Chunk stats: MultiplayerChunkCache: 555, 555
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-236,64,-208), Chunk: (at 4,4,0 in -15,-13; contains blocks -240,0,-208 to -225,255,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 346 game time, 346 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 82 total; [EntityBat['Bat'/130, l='MpServer', x=-256.05, y=19.05, z=-288.50], EntityCow['Cow'/132, l='MpServer', x=-254.08, y=75.00, z=-266.49], EntityCow['Cow'/133, l='MpServer', x=-255.75, y=75.00, z=-268.66], EntityCow['Cow'/134, l='MpServer', x=-252.50, y=75.00, z=-269.50], EntityZombie['Zombie'/135, l='MpServer', x=-250.50, y=28.00, z=-173.50], EntityBat['Bat'/136, l='MpServer', x=-255.57, y=25.14, z=-176.33], EntityChicken['Chicken'/145, l='MpServer', x=-224.50, y=64.00, z=-236.50], EntityChicken['Chicken'/146, l='MpServer', x=-227.50, y=64.00, z=-237.50], EntityChicken['Chicken'/147, l='MpServer', x=-225.50, y=64.00, z=-236.50], EntityChicken['Chicken'/148, l='MpServer', x=-230.60, y=64.00, z=-239.50], EntityCreeper['Creeper'/149, l='MpServer', x=-232.50, y=14.00, z=-196.50], EntityBat['Bat'/150, l='MpServer', x=-229.61, y=16.05, z=-195.50], EntityChicken['Chicken'/157, l='MpServer', x=-224.42, y=70.00, z=-262.83], EntityChicken['Chicken'/158, l='MpServer', x=-222.21, y=70.00, z=-271.10], EntityChicken['Chicken'/159, l='MpServer', x=-213.50, y=68.00, z=-268.50], EntityChicken['Chicken'/160, l='MpServer', x=-213.50, y=68.00, z=-268.50], EntitySkeleton['Skeleton'/161, l='MpServer', x=-222.50, y=35.00, z=-202.50], EntityZombie['Zombie'/162, l='MpServer', x=-222.50, y=37.00, z=-206.50], EntityCreeper['Creeper'/163, l='MpServer', x=-219.50, y=33.00, z=-198.50], EntitySquid['Squid'/164, l='MpServer', x=-222.42, y=47.11, z=-167.26], EntityPetBuddy['ssfoiles'/420, l='MpServer', x=-248.82, y=64.00, z=-216.53], EntitySquid['Squid'/165, l='MpServer', x=-221.63, y=43.52, z=-163.05], EntitySquid['Squid'/166, l='MpServer', x=-214.17, y=46.16, z=-169.93], EntityCreeper['Creeper'/170, l='MpServer', x=-203.50, y=34.00, z=-293.50], EntityBat['Bat'/171, l='MpServer', x=-200.99, y=17.09, z=-279.23], EntityZombie['Zombie'/172, l='MpServer', x=-197.35, y=17.00, z=-277.80], EntityBat['Bat'/173, l='MpServer', x=-202.69, y=21.79, z=-197.78], EntityZombie['Zombie'/174, l='MpServer', x=-197.50, y=31.00, z=-190.50], EntitySquid['Squid'/175, l='MpServer', x=-201.61, y=48.14, z=-166.04], EntitySquid['Squid'/176, l='MpServer', x=-208.47, y=52.88, z=-154.89], EntityCreeper['Creeper'/178, l='MpServer', x=-181.17, y=24.00, z=-281.52], EntityZombie['Zombie'/179, l='MpServer', x=-184.56, y=20.00, z=-284.09], EntityZombie['Zombie'/180, l='MpServer', x=-185.50, y=20.00, z=-286.50], EntityBat['Bat'/181, l='MpServer', x=-182.85, y=32.13, z=-227.45], EntityZombie['Zombie'/182, l='MpServer', x=-186.50, y=14.00, z=-202.50], EntityZombie['Zombie'/183, l='MpServer', x=-184.50, y=14.00, z=-202.50], EntityZombie['Zombie'/184, l='MpServer', x=-182.50, y=15.00, z=-201.50], EntitySpider['Spider'/185, l='MpServer', x=-185.50, y=14.00, z=-202.50], EntitySquid['Squid'/186, l='MpServer', x=-193.31, y=53.55, z=-199.21], EntityCreeper['Creeper'/188, l='MpServer', x=-183.08, y=20.00, z=-189.71], EntityCreeper['Creeper'/189, l='MpServer', x=-183.73, y=20.00, z=-189.62], EntitySpider['Spider'/190, l='MpServer', x=-181.56, y=20.00, z=-188.70], EntityBat['Bat'/66, l='MpServer', x=-313.53, y=27.10, z=-276.15], EntityBat['Bat'/67, l='MpServer', x=-302.56, y=35.59, z=-286.49], EntityCreeper['Creeper'/68, l='MpServer', x=-315.47, y=25.00, z=-273.22], EntitySkeleton['Skeleton'/197, l='MpServer', x=-175.57, y=14.00, z=-234.05], EntityCreeper['Creeper'/198, l='MpServer', x=-173.80, y=15.00, z=-231.56], EntitySpider['Spider'/201, l='MpServer', x=-169.50, y=39.00, z=-218.50], EntityZombie['Zombie'/202, l='MpServer', x=-169.50, y=39.00, z=-218.50], EntitySpider['Spider'/203, l='MpServer', x=-174.50, y=20.00, z=-186.50], EntityPlayerSP['ssfoiles'/310, l='MpServer', x=-248.82, y=64.00, z=-216.53], EntityEnderman['Enderman'/85, l='MpServer', x=-284.50, y=29.00, z=-288.50], EntityChicken['Chicken'/86, l='MpServer', x=-275.50, y=63.00, z=-233.50], EntityChicken['Chicken'/87, l='MpServer', x=-277.49, y=70.00, z=-226.57], EntityChicken['Chicken'/88, l='MpServer', x=-264.77, y=68.00, z=-239.54], EntityCreeper['Creeper'/89, l='MpServer', x=-273.50, y=56.00, z=-210.50], EntityCreeper['Creeper'/90, l='MpServer', x=-277.50, y=57.00, z=-207.50], EntityBat['Bat'/96, l='MpServer', x=-261.72, y=19.10, z=-292.46], EntityZombie['Zombie'/99, l='MpServer', x=-261.70, y=29.00, z=-283.30], EntitySkeleton['Skeleton'/100, l='MpServer', x=-257.24, y=19.00, z=-272.83], EntityItem['item.tile.torch'/102, l='MpServer', x=-260.30, y=34.00, z=-276.16], EntityItem['item.tile.torch'/103, l='MpServer', x=-270.09, y=19.00, z=-266.40], EntityItem['item.tile.gravel'/104, l='MpServer', x=-256.13, y=19.00, z=-263.98], EntityItem['item.tile.gravel'/105, l='MpServer', x=-256.88, y=19.00, z=-265.93], EntityItem['item.tile.gravel'/106, l='MpServer', x=-256.14, y=18.00, z=-260.83], EntityItem['item.tile.gravel'/107, l='MpServer', x=-256.88, y=19.00, z=-261.64], EntityZombie['Zombie'/108, l='MpServer', x=-262.50, y=19.00, z=-265.50], EntityZombie['Zombie'/109, l='MpServer', x=-258.50, y=19.00, z=-267.50], EntityZombie['Zombie'/110, l='MpServer', x=-257.64, y=19.00, z=-271.93], EntityBat['Bat'/111, l='MpServer', x=-250.66, y=35.50, z=-264.40], EntityCow['Cow'/112, l='MpServer', x=-256.15, y=75.00, z=-266.53], EntityBat['Bat'/113, l='MpServer', x=-259.70, y=19.13, z=-255.36], EntityChicken['Chicken'/114, l='MpServer', x=-270.47, y=66.00, z=-239.41], EntityCreeper['Creeper'/115, l='MpServer', x=-269.50, y=27.00, z=-192.50], EntityCreeper['Creeper'/116, l='MpServer', x=-256.50, y=30.00, z=-193.50], EntityCreeper['Creeper'/117, l='MpServer', x=-263.64, y=29.00, z=-196.45], EntityCreeper['Creeper'/118, l='MpServer', x=-260.13, y=30.00, z=-194.74], EntityCreeper['Creeper'/119, l='MpServer', x=-261.50, y=20.00, z=-185.50], EntityZombie['Zombie'/120, l='MpServer', x=-265.54, y=19.00, z=-188.73], EntityEnderman['Enderman'/121, l='MpServer', x=-259.50, y=27.00, z=-179.50], EntitySpider['Spider'/122, l='MpServer', x=-256.50, y=30.00, z=-190.50], EntityCreeper['Creeper'/123, l='MpServer', x=-256.50, y=30.00, z=-190.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2653)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:391)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 938367856 bytes (894 MB) / 1509691392 bytes (1439 MB) up to 8482586624 bytes (8089 MB)
	JVM Flags: 5 total; -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.35 Powered by Forge 13.19.1.2188 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.1.2188.jar) 
	UCHIJAAAA	forge{13.19.1.2188} [Minecraft Forge] (forge-1.11-13.19.1.2188.jar) 
	UCHIJAAAA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (petbuddy-1.11-2.3.1.1.jar) 
	UCHIJAAAA	petbuddy{1.10.2 2.3.1.1} [Pet Buddy] (petbuddy-1.11-2.3.1.1.jar) 
	Loaded coremods (and transformers): 
	Launched Version: 1.11-forge1.11-13.19.1.2188
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GT 750M OpenGL Engine GL version 2.1 NVIDIA-10.10.13 310.42.25f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz

**Comment by AbsolemJackdaw** [comment]
Thanks for the report ! seems i havent updated all itemstack references.
fixing it as we speak.
