### ISSUE TITLE
Pet inventory

### ISSUE THREAD

**Issue by higuita** [ArtixAllMighty/PetBuddy2016#12]
I spawn a pet (had to press P, it didn't show up by itself), build a chest, equipped it and tried to "apply" it to the pet, but nothing happens.
Please clarify how to enable the pet inventory (worst case, open a help window with right click on a inventory-less pet)

**Comment by MurrmorMeerkat** [comment]
Yeah i spawned him but i cant even rightclick him im useing 1.11 so maybe its bugged? cant even acess invintory

**Comment by AbsolemJackdaw** [comment]
i'll look into it. have had more reports about this.

**Comment by AbsolemJackdaw** [comment]
found it. solved.
new version out soon
