### ISSUE TITLE
Crashed on subaraki.petbuddy.entity.EntityPetBuddy.func_184201_a(EntityPetBuddy.java:114)

### ISSUE THREAD

**Issue by Lothrazar** [ArtixAllMighty/PetBuddy2016#17]
I took it in the nether and was just running around.  Is says java.lang.NullPointerException: The validated object is null

https://pastebin.com/KwwP28Xw

**Comment by AbsolemJackdaw** [comment]
funny how i had the same crash as you, fixed it, and pushed a new vesion 4 hours ago ! looks like you forgot to double check if there where any updates available ;) 

but thanks for the reminder, i'll push my code and close this while doing so. 

the update you're looking for is 2.3.1.9 btw

https://minecraft.curseforge.com/projects/pet-buddy-mod/files/2417088
