### ISSUE TITLE
suggestion: tiny buddy dragon

### ISSUE THREAD

**Issue by InkDragon** [ArtixAllMighty/PetBuddy2016#18]
i'd love it if the tiny buddy could take the form of a dragon with either a dragon head or a dragon egg alternatively a gold block could be an option too

**Comment by AbsolemJackdaw** [comment]
I firgot I didn't include all mobs yet ! thanks for the recall. I'm gonna have a busy week, so don't expect anything for the next week or two.

**Comment by InkDragon** [comment]
That's fine ^.=.^ I'm more then happy to wait for something awesome like
that.

When you do it you might want to look at dragon mounts by baracudaATA and
see if you can grab their models since I believe they has small versions
with better animations​. The mod is free to be used as a base for other
mods, so I doubt there will be an issues using the models​.

**Comment by AbsolemJackdaw** [comment]
There's a few mobs I wont be including due to complications, horses and donkeys being one of them. Dragons too. 

I'm going to archive this idea. I'm sorry I couldn't put it in the mod
