### ISSUE TITLE
Ticking memory connection

### ISSUE THREAD

**Issue by jsaggers** [ArtixAllMighty/PetBuddy2016#2]
Updated to version 2.0 and I get a Ticking memory connection crash upon entering the world.
[crash-2016-10-04_11.00.04-server.txt](https://github.com/ArtixAllMighty/PetBuddy2016/files/507418/crash-2016-10-04_11.00.04-server.txt)

**Comment by AbsolemJackdaw** [comment]
PacketSyncOwnInventory : I have found the problem. you can't write null values as an integer. will put up a new version today !
