### ISSUE TITLE
Crash with few mobs

### ISSUE THREAD

**Issue by khinder** [ArtixAllMighty/PetBuddy2016#20]
Hello :) 

I really like this mod because I find it really cool and cute

But with some mobs, the game crash :/
When a charged creeper is about to explose, the game crash, when a witch throw a potion, the game crash (in this case, even if you restart the game, it keep crashing until you delete the mod)

I didn't experienced with every types of mobs, but I think it crash with few other mobs

ps: I have sublib, and sorry for my bad english, this isn't my native language

**Comment by AbsolemJackdaw** [comment]
if you'd have a crash report, i could solve this way faster ! 
will look into the problem

**Comment by AbsolemJackdaw** [comment]
I'm going to concider this has been solved since the merge.
