### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by mooflop** [ArtixAllMighty/PetBuddy2016#25]
this is the first ever mod ive attempted to use but i cant seem to get it to work. i am a noob at these types of things and may need some asistance with the proscess of making the file interact with forge.

**Comment by AbsolemJackdaw** [comment]
While I know this stuff, I will not be the person to help you with it. I'm sure there's a lot of tutorials out there.

the idea is simple.
download forge's installer, install forge. drag the mod file yo udownloaded from curseforge into the mods folder at %appdata% - .minecraft and you should be golden
