### ISSUE TITLE
[Suggestion] Buddy upgrade/leveling system

### ISSUE THREAD

**Issue by Zunlite** [ArtixAllMighty/PetBuddy2016#27]
There are a lot of mods out there that make Minecraft into a very hard game, I dont think that the buddy will be able to stay with me long as the difficulty progresses. So maybe a way to increase the buddy's max health or something would be awesome! Thanks!

**Comment by AbsolemJackdaw** [comment]
thanks for the suggestion ! 
meanwhile , feel free to stash and take your buddy out whenever you see fit using the keybind that comes with the mod (default is 'P' if i recall correctly)

**Comment by AbsolemJackdaw** [comment]
would 80 health max be enough ?

**Comment by AbsolemJackdaw** [comment]
https://streamable.com/6o2vf

a little video i made. crappy quality, but it gets the idea down.
upgradeable health with 1) potion of healing (from 30 to 40)
and 2) a lingering potion of health, (from 40 to 80)

**Comment by AbsolemJackdaw** [comment]
feature has been added in b21122ba50519374ab00d911a858f69165f82d96
