### ISSUE TITLE
Suggestion: Diminutive Name?

### ISSUE THREAD

**Issue by flamablecharlie** [ArtixAllMighty/PetBuddy2016#28]
Would it be possible to add a "diminutive" prefix to the name of the PetBuddy?

Example: In game I am SteampunkCharlie, so my PetBuddy spawns named "SteampunkCharlie" too.

What I'd love to see is the PetBuddy's name have a prefix (possibly configrable?) such as "Mini" or "Lil".

Example: My PetBuddy would become "Mini SteampunkCharlie" or "Lil SteampunkCharlie" instead. Maybe even a "SteampunkCharlie Jr"?

I know you can change their name using a name tag, but that changes their skin as well. If possible, I would want the skin to stay the same, and just add to the name floating above their heads. Aside from that, I love the mod!

**Comment by AbsolemJackdaw** [comment]
I can add a config option to change tiny to anything else. 
might even be in the next update !

**Comment by AbsolemJackdaw** [comment]
also, there's a difference between using a name tag on the buddy, and using a name tag in the appearance slot !
using a named nametag on a pet will not consume the tag, but will name the buddy.

So renaming a buddy will not change their skin. changing skin and renaming are two different actions. or are ought to be. if this is not the case, please do notify me.
