### ISSUE TITLE
Can not respawn

### ISSUE THREAD

**Issue by crookedzro** [ArtixAllMighty/PetBuddy2016#3]
There is no crash report, maybe incompatible with other mods. When I try to respawn, it just sits there on the You Died screen.. I can logout and log back into the server and it still does not respawn but sits on that same screen. 
From the timestamp that it did that, I took the time from the server log.

http://pastebin.com/mQaUt2bS

**Comment by AbsolemJackdaw** [comment]
No, it's an internal problem. I'm having difficulties tracking the problem down, but I might have fixed it. as we are speaking, I'm compiling v2.2 of the PetBuddy mod. 
I'm going to close this, and if the problem persists, please come back and re-report it !
Note: someone else also gave me a crash of the same allure. You're not alone ! =)
