### ISSUE TITLE
Inventory Server Crash

### ISSUE THREAD

**Issue by WenXin20** [ArtixAllMighty/PetBuddy2016#31]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Pet Buddy v3.0.0.0`

As soon as I placed an item (sticks) in the pet buddy inventory, my server crashed.
[Crash Report](https://gist.github.com/WenXin20/c7e886670aacba463ee449d0a253c56d)

**Comment by AbsolemJackdaw** [comment]
thanks for the crash. The mod has been toroughly tested, though we couldn't test on a dedicated server. 
I'll push a fix for this and will try to upload a fixed version asap.

**Comment by WenXin20** [comment]
Thanks!

**Comment by WenXin20** [comment]
Oh yeah, I also forgot to mention that the background isn't darkened the way other inventory screens are.
