### ISSUE TITLE
Name Glitch

### ISSUE THREAD

**Issue by ReddPyramid** [ArtixAllMighty/PetBuddy2016#4]
So I gave the mod a try, and I love it, but there is a problem with how its name is displayed.  I'd also like to be able to rename it and googling hasn't turned up any answers on how to do that.  So-

-How do I fix the name display?
-Is there a way to rename it?

Example of name glitch:

![2016-10-05_10 43 12](https://cloud.githubusercontent.com/assets/13576885/19122672/c925694c-8ae8-11e6-948f-be49fa9a05ee.png)

**Comment by tacogerbil** [comment]
I'm getting the same thing as well.. including that nothing happens when I right click him.. does anything similar happen to you?

**Comment by AbsolemJackdaw** [comment]
Thanks for the name glitch ! i've had more then one report of it. What is your in - game name ? 

-Yes, you can rename them with a name tag.
-you need to give them a chest to right click them and open the inventory.
the above info can be all found in the wiki on this github =) !

**Comment by AbsolemJackdaw** [comment]
Found the possible base of the error, 

Minecraft uses §0 - §F for formatting color. for some reason it's not working on your computer(s).

https://github.com/ArtixAllMighty/PetBuddy2016/issues/5#issuecomment-252303336
