### ISSUE TITLE
Right clicking

### ISSUE THREAD

**Issue by tacogerbil** [ArtixAllMighty/PetBuddy2016#5]
It does nothing.  I've tried all combinations... nothing happens.  I also have the name glitch where there is a ?2 before the name

**Comment by AbsolemJackdaw** [comment]
interact with buddy :  https://github.com/ArtixAllMighty/PetBuddy2016/wiki/Gui#what-my-buddy-can-do
- Buddies with good health show a green color ... 
  https://github.com/ArtixAllMighty/PetBuddy2016/wiki/Gui#heal-your-pet-buddy-
- And I think i just figured out the name glitch...
  http://minecraft.gamepedia.com/Formatting_codes#Color_codes  

For some reason the formating isn't working for you, nor the other people.
