### ISSUE TITLE
suggestions: ranged attack

### ISSUE THREAD

**Issue by GrzechuGrek** [ArtixAllMighty/PetBuddy2016#7]
Give him bow to shoot at enemies.

Give him a snowballs or eggs and will throw it at enemies.
If give him a cobblestone, then he crush to few small pebbles and throw these at enemies to deal him some damage

**Comment by AbsolemJackdaw** [comment]
I like this idea. I'll try to add in the bow option to make him shoot some arrows. i'll try to figure out where the arrows come from

**Comment by lag42** [comment]
just make it require a chest to hold arrows its just 8 wood planks/2 logs chances are you can make one if you have a bow

**Comment by AbsolemJackdaw** [comment]
I'm still thinkering on this idea. please stay with me while i process this !

**Comment by AbsolemJackdaw** [comment]
The idea has been around for long, but I never found the time to put it into the game.
I'm going to archive this idea. Sorry I never put it in.
