### ISSUE TITLE
Suggestion: Pet Buddy dmg counting as player dmg. & weapon support.

### ISSUE THREAD

**Issue by Kaisoul** [ArtixAllMighty/PetBuddy2016#9]
Loving my little buddy with me but with mods that only drop its loot with player dmg my buddy if i let him fight with me is more of a problem then a help do to that one draw back.

Also looks like the buddy does not like tinker construct weapons or is this all non-vanilla weapons?
weapon issue is a small draw back but would like the buddy to have the ability with in reason be able to use a decent variety of weapons.

**Comment by AbsolemJackdaw** [comment]
weapons only work if they are an instance of ItemSword. (currently)

I'll make the pet deal player damage. sounds like a plan.

**Comment by AbsolemJackdaw** [comment]
they should now deal player and mob damage
